### ISSUE TITLE
No Remove Methods?

### ISSUE THREAD

**Issue by andreaalloway** [BatmanAMA/powerbox#19]
Is there a plan to add the Remove methods to the PowerShell library?
Adding and Setting is great!
It would be nice to automatically remove assets.

**Comment by BatmanAMA** [comment]
Ah, I didn't even think of that. I'm handling removes as a manual event because old asset management locations I've built ran into issues with things randomly disappearing on me. I have some automated scripts that change the assets' status to "offline" and then I have a manual effort to review things in offline state and clean them up or fix them weekly.

I'll add this to my list for the next update.
